# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Cologne', max_length=60)),
                ('postcode', models.IntegerField(blank=True)),
                ('laundry', models.IntegerField(blank=True, default='weight in KG')),
                ('description', models.TextField(help_text='For important message')),
            ],
        ),
    ]
