# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='name',
            field=models.CharField(default='name of the customer', max_length=120),
        ),
    ]
