# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_laundry_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundry',
            old_name='laundry',
            new_name='laundryweight',
        ),
    ]
