# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_auto_20180815_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='location',
            field=models.CharField(help_text='Cologne', max_length=60),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='name',
            field=models.CharField(help_text='name of the customer', max_length=120),
        ),
    ]
